# Site settings
title: lemonade
alter_title: smashed_lemons
email: miss.mino.fiona@gmail.com
description: (no sugar added)

author:
  name     : 'Smashedlemons'
  email    : miss.mino.fiona@gmail.com
  twitter  : http://twitter.com/smashed_lemons

github: https://github.com/smashedlemons
disqus_shortname: ""
google_analytics:

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/

baseurl: https://smashedlemons.github.io
